# name: ğŸ§ª Tests

# on:
#   push:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     container:
#       image: osgeo/gdal:ubuntu-small-3.6.3

#     steps:
#     - name: ğŸ“‚ Checkout
#       uses: actions/checkout@v4

#     - name: â¬ Install dependencies
#       run: |
#         apt-get update && apt-get install ffmpeg libsm6 libxext6 python3-pip -y
#         pip install --upgrade pip
#         pip install -r requirements.test.txt

#     - name: âœ… Run tests
#       run: |
#         pytest test
